#!/usr/bin/env bash

# Set the filename of the private key
PRIVATE_KEY_FILENAME="school"

# Set the number of bits in the key
KEY_SIZE=4096

# Set the passphrase to protect the key
PASSPHRASE="betty"

# Generate the key pair
ssh-keygen -t rsa -b $KEY_SIZE -N $PASSPHRASE -f $PRIVATE_KEY_FILENAME

